name: 'release'
on: 
  release:

jobs:
  package-and-publish: 
    runs-on: ubuntu-latest
    steps:
      - name: Checking out!
        uses: actions/checkout@v3
        
      - name: Publish action package
        uses: ./